# 프로덕션
version: '3.8'

services:
  backend:
    image: ${ECR_REGISTRY:-local}/${ECR_BACKEND:-aramtax-backend}:latest
    build: ./backend
    expose:
      - "8000"
    env_file:
      - ./backend/.env
    restart: unlesss-stopped

  frontend:
    image: ${ECR_REGISTRY:-local}/${ECR_FRONTEND:-aramtax-frontend}:latest
    build: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    restart: unless_stopped